@apiUrl = https://fw-teaching.fi/demo/wdbocms/api/v1

# Get alla produkter
GET {{apiUrl}}/products

### 
# GET en produkt
GET {{apiUrl}}/products/1002

###
# POST skapa produkt
POST {{apiUrl}}/products/
Content-Type: application/json

{
    "name": "Jeans",
    "price": 77
}

###
# PUT ändra en produkt
PUT {{apiUrl}}/products/1005
Content-Type: application/json

{
    "name": "Chinos",
    "price": 88
}

###
# PATCH ändra fält i en produkt
PATCH {{apiUrl}}/products/1005
Content-Type: application/json

{
    "price": 99
}